"use strict";
// Science Quest — topic: Life Cycles (MOE 2023 Primary Science, Cycles theme, P3).
// Data only; the small helpers below only build SVG / HTML strings (no DOM access).
(function () {
  const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const FONT = 'font-family="system-ui, -apple-system, sans-serif"';

  // Labelled stage cycle: boxes placed round an ellipse, arrows clockwise.
  // '|' in a label breaks it onto two lines. A label of '?' or a single letter is drawn dashed.
  function cycle(labels) {
    const n = labels.length, W = 360, H = 260, cx = 180, cy = 130, rx = 118, ry = 88, bw = 118, bh = 40;
    const pts = labels.map((_, i) => {
      const a = -Math.PI / 2 + (2 * Math.PI * i) / n;
      return [cx + rx * Math.cos(a), cy + ry * Math.sin(a)];
    });
    let out = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="100%" style="max-width:360px" role="img" aria-label="Life cycle diagram: ${esc(labels.join(', then ').replace(/\|/g, ' '))}, then back to the start" ${FONT}>`;
    for (let i = 0; i < n; i++) {
      const [px, py] = pts[i], [qx, qy] = pts[(i + 1) % n];
      const dx = qx - px, dy = qy - py, d = Math.hypot(dx, dy), ux = dx / d, uy = dy / d;
      const cut = Math.min(Math.abs(ux) > 1e-6 ? bw / 2 / Math.abs(ux) : 1e9, Math.abs(uy) > 1e-6 ? bh / 2 / Math.abs(uy) : 1e9) + 5;
      const sx = px + ux * cut, sy = py + uy * cut, ex = qx - ux * cut, ey = qy - uy * cut;
      const hx = ex - ux * 10, hy = ey - uy * 10, nx = -uy * 5, ny = ux * 5;
      out += `<line x1="${sx.toFixed(1)}" y1="${sy.toFixed(1)}" x2="${hx.toFixed(1)}" y2="${hy.toFixed(1)}" stroke="currentColor" stroke-width="2"/>`;
      out += `<polygon points="${ex.toFixed(1)},${ey.toFixed(1)} ${(hx + nx).toFixed(1)},${(hy + ny).toFixed(1)} ${(hx - nx).toFixed(1)},${(hy - ny).toFixed(1)}" fill="currentColor"/>`;
    }
    labels.forEach((lab, i) => {
      const [px, py] = pts[i];
      const unknown = lab === '?' || /^[A-Z]$/.test(lab);
      out += `<rect x="${(px - bw / 2).toFixed(1)}" y="${(py - bh / 2).toFixed(1)}" width="${bw}" height="${bh}" rx="8" fill="none" stroke="currentColor" stroke-width="${unknown ? 2.5 : 1.5}"${unknown ? ' stroke-dasharray="5 4"' : ''}/>`;
      const lines = lab.split('|');
      lines.forEach((t, k) => {
        const y = py + (k - (lines.length - 1) / 2) * 15 + 5;
        out += `<text x="${px.toFixed(1)}" y="${y.toFixed(1)}" text-anchor="middle" font-size="${unknown ? 18 : 13}" font-weight="${unknown ? 700 : 500}" fill="currentColor">${esc(t)}</text>`;
      });
    });
    return out + '</svg>';
  }

  // Simple bordered HTML table. Cells are trusted plain strings (escaped here).
  function tbl(head, rows, caption) {
    const td = 'style="border:1px solid currentColor;padding:4px 8px;text-align:center"';
    let h = '<table style="border-collapse:collapse;margin:0 auto;font-size:14px">';
    if (caption) h += `<caption style="padding-bottom:4px;font-weight:600">${esc(caption)}</caption>`;
    h += '<tr>' + head.map((c) => `<th ${td}>${esc(c)}</th>`).join('') + '</tr>';
    rows.forEach((r) => { h += '<tr>' + r.map((c) => `<td ${td}>${esc(c)}</td>`).join('') + '</tr>'; });
    return h + '</table>';
  }

  const daysTable = tbl(['Stage', 'Egg', 'Larva', 'Pupa', 'Adult'], [['Number of days', '4', '18', '9', '14']], 'Days animal X spent in each stage');

  const germTable4 = tbl(
    ['Set-up', 'Water', 'Air', 'Warmth', 'Light'],
    [['A', 'Yes', 'Yes', 'Yes', 'Yes'], ['B', 'No', 'Yes', 'Yes', 'Yes'], ['C', 'Yes', 'Yes', 'No (cold)', 'Yes'], ['D', 'Yes', 'Yes', 'Yes', 'No (dark)']],
    'Was each condition given to the seeds?');

  const fairPick = tbl(
    ['Set-up', 'Cotton wool', 'Temperature', 'Light'],
    [['P', 'wet', '25°C', 'light'], ['Q', 'dry', '25°C', 'light'], ['R', 'dry', '5°C', 'dark'], ['S', 'wet', '5°C', 'light']],
    'Each dish has 10 green bean seeds');

  const meiExp = tbl(
    ['Dish', 'Cotton wool', 'Place', 'Number of seeds', 'Seeds that germinated after 5 days'],
    [['A', 'wet', 'on the table', '10', '9'], ['B', 'dry', 'on the table', '10', '0']],
    "Mei's experiment");

  const fridgeExp = tbl(
    ['Set-up', 'Cotton wool', 'Placed', 'Germinated?'],
    [['A', 'wet', 'on a sunny windowsill', 'Yes'], ['B', 'wet', 'inside a fridge', 'No']],
    "Ali's experiment");

  const threeAnimals = tbl(
    ['Animal', 'Stages in its life cycle'],
    [['A', 'egg → nymph → adult'], ['B', 'egg → larva → pupa → adult'], ['C', 'egg → tadpole → froglet → adult']]);

  const compareTable = tbl(
    ['Animal', 'Stages in its life cycle'],
    [['Cockroach', 'egg → nymph → adult'], ['Butterfly', 'egg → larva → pupa → adult']]);

  SCI.registerTopic({
    id: 'life-cycles',
    title: 'Life Cycles',
    emoji: '🦋',
    theme: 'Cycles',
    moeRef: 'Cycles in Plants and Animals: show an understanding that different living things have different life cycles; observe and compare the life cycles of plants grown from seeds and of animals over a period of time (para)',
    notes: [
      { title: 'What is a life cycle?',
        body: 'A life cycle is the stages a living thing goes through from the start of its life (an egg or a seed) until it becomes an adult that can reproduce. The adult lays eggs or makes seeds, so the cycle starts again. This makes sure its kind does not die out. Different living things have different life cycles, with different numbers of stages.' },
      { title: '4-stage life cycles',
        body: 'Egg → larva → pupa → adult. Butterfly, moth, mosquito, beetle and housefly have 4 stages. The young (larva) does NOT look like the adult. The larva feeds the most and grows the fastest. The pupa does NOT feed; inside it, the body changes into the adult.' },
      { title: 'The butterfly',
        body: 'Egg: laid on (usually the underside of) leaves the caterpillar can eat. Larva (caterpillar): eats a lot, grows, and sheds its skin (moults) several times so it can grow bigger. Pupa (chrysalis): does not feed and hardly moves — it is alive and changing into a butterfly. Adult: has wings, sucks nectar from flowers, mates and lays eggs.' },
      { title: 'The mosquito',
        body: 'Egg → larva → pupa → adult (4 stages). Eggs are laid on the surface of still (stagnant) water. The larva and pupa live in water and come to the surface to take in air. The larva feeds; the pupa does NOT feed but can still move about in the water. Only the adult can fly. Removing stagnant water stops mosquitoes from completing their life cycle, so there are fewer mosquitoes to spread dengue.' },
      { title: '3-stage life cycles',
        body: 'Egg → nymph → adult. Cockroach and grasshopper have 3 stages and NO pupa stage. The nymph looks like the adult but is smaller and has no wings. It moults (sheds its skin) several times as it grows. The chicken also has 3 stages: egg → chick → adult chicken. The young of the cockroach, grasshopper and chicken looks like the adult.' },
      { title: 'The frog',
        body: 'Egg → tadpole → froglet (young frog) → adult frog. Eggs are laid in water in a jelly. A tadpole lives only in water, has a tail and no legs at first. Back legs grow first, then front legs, while the tail gets shorter. A froglet has four legs and a short tail. The adult frog has no tail and can live on land and in water. The tadpole does not look like the adult. Some books show only 3 stages (egg → tadpole → adult frog) and leave out the froglet; follow the diagram in your question.' },
      { title: 'The life cycle of a flowering plant',
        body: 'Seed → seedling → young plant → adult plant. The adult plant has flowers, which develop into fruits with seeds inside. When a seed germinates (starts to grow), the seed coat splits, the root grows out first and grows downwards, then the shoot grows upwards. The seed leaves hold stored food for the seedling; they shrivel and drop off when the food is used up.' },
      { title: 'Germination and fair tests',
        body: 'A seed needs water, air and warmth (a suitable temperature) to germinate. It does NOT need light or soil to germinate — seeds on wet cotton wool in a dark cupboard still germinate. In a fair test, change only ONE thing (the variable you are testing) and keep everything else the same. Use many seeds (e.g. 10) in each set-up so the result is reliable, because some seeds may not germinate anyway.' },
      { title: 'How to compare two life cycles',
        body: 'Ask: (1) How many stages? (2) Is there a pupa stage? (3) Does the young look like the adult? (4) Which stage does not feed / feeds the most? (5) Where does each stage live (water or land)? A similarity: both start as eggs / both have an adult stage. A difference: e.g. a butterfly has a pupa stage but a cockroach does not.' }
    ],
    items: [
      // ---------- MCQ ----------
      { id: 'lc-001', type: 'mcq', level: 1,
        stem: 'What is the correct order of the stages in the life cycle of a butterfly?',
        figure: null,
        options: ['Egg → pupa → larva → adult', 'Egg → nymph → adult', 'Larva → egg → pupa → adult', 'Egg → larva → pupa → adult'],
        answer: 3,
        explain: 'A butterfly starts as an egg. A larva (caterpillar) hatches, becomes a pupa, and an adult butterfly comes out of the pupa.' },
      { id: 'lc-002', type: 'mcq', level: 1,
        stem: 'How many stages are there in the life cycle of a mosquito?',
        figure: null,
        options: ['2', '3', '4', '5'],
        answer: 2,
        explain: 'A mosquito has 4 stages: egg, larva, pupa and adult — the same pattern as a butterfly.' },
      { id: 'lc-003', type: 'mcq', level: 1,
        stem: 'What is the young of a cockroach called?',
        figure: null,
        options: ['Larva', 'Pupa', 'Nymph', 'Tadpole'],
        answer: 2,
        explain: 'The cockroach has a 3-stage life cycle: egg → nymph → adult. The nymph looks like the adult but is smaller and has no wings.' },
      { id: 'lc-004', type: 'mcq', level: 1,
        stem: 'Which stage of a butterfly feeds the most?',
        figure: null,
        options: ['Egg', 'Larva (caterpillar)', 'Pupa', 'Adult'],
        answer: 1,
        explain: 'The caterpillar eats leaves all the time and grows very fast. The egg and the pupa do not feed at all.' },
      { id: 'lc-005', type: 'mcq', level: 1,
        stem: 'During which stage does a butterfly NOT feed, while its body changes into an adult inside a hard case?',
        figure: null,
        options: ['Egg', 'Larva', 'Adult', 'Pupa'],
        answer: 3,
        explain: 'The pupa (chrysalis) does not feed and hardly moves, but it is alive — inside the hard case the body is changing into a butterfly.' },
      { id: 'lc-006', type: 'mcq', level: 1,
        stem: 'What is a young frog with four legs and a short tail called?',
        figure: null,
        options: ['Tadpole', 'Nymph', 'Froglet', 'Larva'],
        answer: 2,
        explain: 'A froglet (young frog) has four legs and a short tail that will disappear when it becomes an adult frog. It comes after the tadpole stage.' },
      { id: 'lc-007', type: 'mcq', level: 1,
        stem: 'Which animal has a life cycle with only 3 stages?',
        figure: null,
        options: ['Butterfly', 'Mosquito', 'Beetle', 'Grasshopper'],
        answer: 3,
        explain: 'Grasshopper: egg → nymph → adult (3 stages). Butterfly, mosquito and beetle all have 4 stages with a pupa.' },
      { id: 'lc-008', type: 'mcq', level: 1,
        stem: 'Which animal has a life cycle with 4 stages?',
        figure: null,
        options: ['Cockroach', 'Beetle', 'Grasshopper', 'Chicken'],
        answer: 1,
        explain: 'A beetle has egg, larva, pupa and adult stages. Cockroach and grasshopper go egg → nymph → adult, and a chicken goes egg → chick → adult.' },
      { id: 'lc-009', type: 'mcq', level: 1,
        stem: 'What is germination?',
        figure: null,
        options: ['When a seed starts to grow into a new plant', 'When a flower turns into a fruit', 'When a plant makes new seeds', 'When a seed is carried away from its parent plant'],
        answer: 0,
        explain: 'Germination is when a seed starts to grow. The seed coat splits and a root, then a shoot, grow out.' },
      { id: 'lc-010', type: 'mcq', level: 1,
        stem: 'When a seed germinates, which part grows out of the seed first?',
        figure: null,
        options: ['The shoot', 'The leaves', 'The root', 'The flower'],
        answer: 2,
        explain: 'The root comes out first and grows downwards to hold the seedling in place and take in water. The shoot comes out after.' },
      { id: 'lc-011', type: 'mcq', level: 1,
        stem: 'Which of these does a seed need in order to germinate?',
        figure: null,
        options: ['Water, light and soil', 'Air, light and soil', 'Water, air and warmth', 'Water, soil and fertiliser'],
        answer: 2,
        explain: 'A seed needs water, air and warmth to germinate. It does not need light or soil — seeds can germinate on wet cotton wool in the dark.' },
      { id: 'lc-012', type: 'mcq', level: 1,
        stem: 'The diagram shows the life cycle of a butterfly. What is stage A?',
        figure: cycle(['Egg', 'A', 'Pupa', 'Adult']),
        options: ['Nymph', 'Larva (caterpillar)', 'Tadpole', 'Seedling'],
        answer: 1,
        explain: 'Between the egg and the pupa is the larva, which for a butterfly is called a caterpillar.' },
      { id: 'lc-013', type: 'mcq', level: 1,
        stem: 'The diagram shows the life cycle of a mosquito. What is stage X?',
        figure: cycle(['Egg', 'Larva', 'X', 'Adult']),
        options: ['Pupa', 'Nymph', 'Froglet', 'Egg'],
        answer: 0,
        explain: 'Mosquito: egg → larva → pupa → adult. After the larva comes the pupa, which lives in water and does not feed.' },
      { id: 'lc-014', type: 'mcq', level: 2,
        stem: 'The diagram shows the life cycle of a frog. What is the missing stage?',
        figure: cycle(['Egg', 'Tadpole', '?', 'Adult frog']),
        options: ['Pupa', 'Nymph', 'Larva', 'Froglet'],
        answer: 3,
        explain: 'After the tadpole grows legs and its tail gets shorter, it is a froglet (young frog). Then it grows into an adult frog.' },
      { id: 'lc-015', type: 'mcq', level: 2,
        stem: 'Where does a mosquito usually lay its eggs?',
        figure: null,
        options: ['On the underside of leaves', 'In dry soil', 'Inside fruits', 'On the surface of still (stagnant) water'],
        answer: 3,
        explain: 'Mosquitoes lay eggs on still water. The larva and pupa that hatch live in the water.' },
      { id: 'lc-016', type: 'mcq', level: 2,
        stem: 'We are told to turn over pails and empty water from flower-pot plates. How does this help to reduce the number of mosquitoes?',
        figure: null,
        options: ['The larva and pupa live in water, so the life cycle is broken', 'Adult mosquitoes need the water to drink, so they will die of thirst', 'Mosquito eggs can only hatch on dry ground, so the eggs will dry up', 'The water helps the wings of young mosquitoes to grow'],
        answer: 0,
        explain: 'The egg, larva and pupa of the mosquito all need water. No stagnant water means the life cycle is broken and fewer adults are produced.' },
      { id: 'lc-017', type: 'mcq', level: 2,
        stem: 'Which statement about a cockroach nymph is correct?',
        figure: null,
        options: ['It looks like the adult but has no wings', 'It does not feed until it becomes an adult', 'It will turn into a pupa before it becomes an adult', 'It lives in water and breathes at the surface'],
        answer: 0,
        explain: 'A nymph looks like a small adult without wings. It feeds, moults as it grows, and becomes an adult directly — there is no pupa stage.' },
      { id: 'lc-018', type: 'mcq', level: 2,
        stem: 'In which pair do BOTH animals have young that look like their adults?',
        figure: null,
        options: ['Butterfly and frog', 'Mosquito and grasshopper', 'Chicken and cockroach', 'Beetle and chicken'],
        answer: 2,
        explain: 'A chick looks like a small chicken, and a cockroach nymph looks like a small cockroach without wings. Butterfly, frog, mosquito and beetle young look very different from their adults.' },
      { id: 'lc-019', type: 'mcq', level: 2,
        stem: 'What is one similarity between the life cycle of a butterfly and the life cycle of a mosquito?',
        figure: null,
        options: ['Both have a pupa stage', 'Both lay their eggs in water', 'Both larvae live on land', 'Both have 3 stages'],
        answer: 0,
        explain: 'Both have 4 stages: egg, larva, pupa and adult. Only the mosquito lays eggs in water and has larvae that live in water.' },
      { id: 'lc-020', type: 'mcq', level: 2,
        stem: 'What is one difference between the life cycle of a grasshopper and the life cycle of a beetle?',
        figure: null,
        options: ['The grasshopper does not lay eggs', 'The beetle has a nymph stage', 'The grasshopper has no pupa stage', 'The young grasshopper does not look like its adult'],
        answer: 2,
        explain: 'Grasshopper: egg → nymph → adult (no pupa). Beetle: egg → larva → pupa → adult. Both lay eggs.' },
      { id: 'lc-021', type: 'mcq', level: 2,
        stem: 'The table shows the number of days animal X spent in each stage of its life cycle. In which stage did it spend the longest time?',
        figure: daysTable,
        options: ['Egg', 'Larva', 'Pupa', 'Adult'],
        answer: 1,
        explain: 'Compare the numbers: egg 4, larva 18, pupa 9, adult 14. The largest is 18 days, the larva stage.' },
      { id: 'lc-022', type: 'mcq', level: 2,
        stem: 'Look at the same table. How many days after the egg was laid did the adult of animal X come out?',
        figure: daysTable,
        options: ['22 days', '27 days', '31 days', '45 days'],
        answer: 2,
        explain: 'The adult comes out after the egg, larva and pupa stages: 4 + 18 + 9 = 31 days. Do not add the 14 days of the adult stage.' },
      { id: 'lc-023', type: 'mcq', level: 2,
        stem: 'A caterpillar sheds its skin several times. Why?',
        figure: null,
        options: ['So that it can grow bigger', 'So that it can turn into an adult at once', 'To keep itself warm', 'Because it is sick'],
        answer: 0,
        explain: 'The caterpillar\'s skin does not grow with it, so it sheds (moults) the old skin to grow bigger. Nymphs of cockroaches and grasshoppers moult too.' },
      { id: 'lc-024', type: 'mcq', level: 2,
        stem: 'The boxes show four stages of a plant\'s life cycle, mixed up. Which is the correct order?',
        figure: tbl(['P', 'Q', 'R', 'S'], [['Young plant', 'Seed', 'Adult plant with flowers and fruits', 'Seedling']]),
        options: ['Q → P → S → R', 'Q → S → P → R', 'S → Q → P → R', 'R → Q → S → P'],
        answer: 1,
        explain: 'Seed (Q) → seedling (S) → young plant (P) → adult plant with flowers and fruits (R). The fruits hold seeds, so the cycle starts again.' },
      { id: 'lc-025', type: 'mcq', level: 2,
        stem: 'Which describes a tadpole that has just hatched?',
        figure: null,
        options: ['It has four legs and no tail', 'It has two legs and lives on land', 'It has wings', 'It has a tail and no legs'],
        answer: 3,
        explain: 'A newly hatched tadpole lives in water and has a tail but no legs. Legs grow later, back legs first.' },
      { id: 'lc-026', type: 'mcq', level: 1,
        stem: 'Which of these is NOT a stage in the life cycle of a frog?',
        figure: null,
        options: ['Egg', 'Tadpole', 'Pupa', 'Adult'],
        answer: 2,
        explain: 'Frog: egg → tadpole → (froglet) → adult. A pupa stage is found in insects like the butterfly and mosquito, not in frogs.' },
      { id: 'lc-027', type: 'mcq', level: 3,
        stem: 'Green bean seeds were given the conditions in the table. In which set-up(s) would the seeds germinate?',
        figure: germTable4,
        options: ['A only', 'A and D only', 'A, B and D only', 'A, B, C and D'],
        answer: 1,
        explain: 'Seeds need water, air and warmth. A and D have all three. Light is not needed, so D (dark) still germinates. B has no water and C is too cold.' },
      { id: 'lc-028', type: 'mcq', level: 3,
        stem: 'Ali wants to find out if seeds need water to germinate. Which TWO set-ups should he compare?',
        figure: fairPick,
        options: ['P and R', 'P and Q', 'Q and S', 'R and S'],
        answer: 1,
        explain: 'P and Q differ ONLY in water (wet vs dry); temperature and light are the same. That is a fair test. Q and S also differ in temperature; R and S also differ in light.' },
      { id: 'lc-029', type: 'mcq', level: 3,
        stem: 'Mei put 10 seeds in each dish instead of only 1 seed. Why?',
        figure: null,
        options: ['So that the seeds will germinate faster', 'So that the result is more reliable', 'So that the plants will grow taller', 'So that less water is needed'],
        answer: 1,
        explain: 'One seed might be damaged or dead and not germinate for a reason that has nothing to do with the test. Using many seeds makes the result more reliable.' },
      { id: 'lc-030', type: 'mcq', level: 3,
        stem: 'Which stage of a mosquito does NOT feed but can still move about in the water?',
        figure: null,
        options: ['Egg', 'Larva', 'Adult', 'Pupa'],
        answer: 3,
        explain: 'The mosquito pupa does not feed but can tumble and move about in the water. The egg cannot move, and the larva and adult both feed.' },
      { id: 'lc-031', type: 'mcq', level: 3,
        stem: 'The diagram shows the life cycle of an animal. Stage Y looks like the adult but is smaller and has no wings. Which animal could it be?',
        figure: cycle(['Egg', 'Y', 'Adult']),
        options: ['Butterfly', 'Frog', 'Cockroach', 'Mosquito'],
        answer: 2,
        explain: 'A 3-stage life cycle with a young that looks like the adult but has no wings: egg → nymph → adult. That is the cockroach.' },
      { id: 'lc-032', type: 'mcq', level: 3,
        stem: 'A few days after a seed germinates, its seed leaves become smaller, shrivel and drop off. Why?',
        figure: null,
        options: ['The seedling has used up the food stored in the seed leaves', 'The seedling did not get enough light', 'Insects have eaten the seed leaves', 'The seed leaves have turned into roots'],
        answer: 0,
        explain: 'The seed leaves store food for the young seedling. As the seedling grows, it uses up this food, so the seed leaves shrivel and fall off.' },
      { id: 'lc-033', type: 'mcq', level: 2,
        stem: 'Which statement about life cycles is correct?',
        figure: null,
        options: ['All animals have 4 stages in their life cycle', 'All young animals look like their parents', 'Plants do not have life cycles', 'Different animals can have different numbers of stages'],
        answer: 3,
        explain: 'A butterfly has 4 stages but a cockroach has 3. Plants have life cycles too: seed → seedling → young plant → adult plant.' },

      // ---------- OEQ ----------
      { id: 'lc-040', type: 'oeq', level: 1, marks: 2,
        stem: 'Name the four stages in the life cycle of a butterfly, in the correct order.',
        figure: null,
        model: 'Egg → larva (caterpillar) → pupa (chrysalis) → adult butterfly.',
        keys: [['larva', 'caterpillar'], ['pupa', 'chrysalis']],
        explain: 'Markers look for larva/caterpillar and pupa in the middle, in the right order between egg and adult.' },
      { id: 'lc-041', type: 'oeq', level: 1, marks: 1,
        stem: 'What is the young of a grasshopper called?',
        figure: null,
        model: 'A nymph.',
        keys: [['nymph']],
        explain: 'Grasshoppers and cockroaches: egg → nymph → adult. Do not call it a larva.' },
      { id: 'lc-042', type: 'oeq', level: 1, marks: 3,
        stem: 'State the three conditions a seed needs in order to germinate.',
        figure: null,
        model: 'Water, air and warmth (a suitable temperature).',
        keys: [['water'], ['air', 'oxygen'], ['warmth', 'warm', 'suitable temperature']],
        explain: 'Light and soil are NOT needed for germination — a common trap.' },
      { id: 'lc-043', type: 'oeq', level: 1, marks: 1,
        stem: 'In the life cycle of a plant, which stage comes right after the seed?',
        figure: null,
        model: 'The seedling.',
        keys: [['seedling']],
        explain: 'Seed → seedling → young plant → adult plant.' },
      { id: 'lc-044', type: 'oeq', level: 2, marks: 2,
        stem: 'State two ways in which a newly hatched tadpole is different from an adult frog.',
        figure: null,
        model: 'A tadpole has a tail but an adult frog has no tail. A tadpole has no legs but an adult frog has four legs. (Also accepted: a tadpole lives only in water but an adult frog can live on land and in water.)',
        keys: [['tail'], ['legs', 'land']],
        explain: 'Each difference must compare BOTH animals, e.g. "tadpole has a tail BUT the adult frog has no tail".' },
      { id: 'lc-045', type: 'oeq', level: 2, marks: 2,
        stem: 'People are told to remove stagnant water around their homes. Using the life cycle of the mosquito, explain how this helps.',
        figure: null,
        model: 'Mosquitoes lay their eggs in stagnant water, and the larvae and pupae live in water. Without stagnant water, mosquitoes cannot complete their life cycle, so there will be fewer adult mosquitoes.',
        keys: [['lay eggs', 'larva', 'larvae', 'pupa', 'pupae', 'breed'], ['cannot complete', 'life cycle', 'fewer mosquitoes', 'fewer adult']],
        explain: 'Point 1: which stages need water. Point 2: the life cycle is broken, so fewer mosquitoes.' },
      { id: 'lc-046', type: 'oeq', level: 2, marks: 2,
        stem: 'Look at the table. State one similarity and one difference between the life cycles of the cockroach and the butterfly.',
        figure: compareTable,
        model: 'Similarity: both start as eggs / both have an egg and an adult stage. Difference: the butterfly has a pupa stage but the cockroach does not (cockroach has 3 stages, butterfly has 4).',
        keys: [['egg', 'adult', 'both'], ['pupa', 'nymph', 'number of stages', '3 stages', '4 stages', 'three', 'four']],
        explain: 'For a difference, mention both animals: "the butterfly has a pupa stage BUT the cockroach does not".' },
      { id: 'lc-047', type: 'oeq', level: 2, marks: 2,
        stem: 'The pupa of a butterfly does not eat. Explain how it can still stay alive and change into an adult.',
        figure: null,
        model: 'As a caterpillar (larva), it ate a lot of food. The pupa uses the food stored from the larva stage.',
        keys: [['caterpillar', 'larva'], ['food', 'ate', 'stored']],
        explain: 'This is why the larva stage feeds the most — it stores food for the pupa stage.' },
      { id: 'lc-048', type: 'oeq', level: 1, marks: 1,
        stem: 'A cockroach nymph sheds its skin several times. Why does it do this?',
        figure: null,
        model: 'So that it can grow bigger.',
        keys: [['grow', 'bigger']],
        explain: 'Its outer covering cannot grow, so it sheds it to grow bigger. This is called moulting.' },
      { id: 'lc-049', type: 'oeq', level: 3, marks: 2,
        stem: 'Ali set up the experiment in the table. Seeds in A germinated; seeds in B did not. Ali concluded: "Seeds need light to germinate." Explain why his conclusion is not correct.',
        figure: fridgeExp,
        model: 'It is not a fair test because two things were changed: light and temperature (the fridge is dark AND cold). The seeds in B did not germinate because it was too cold — seeds need warmth, not light.',
        keys: [['two', 'more than one', 'not a fair test', 'light and temperature'], ['cold', 'warmth', 'temperature']],
        explain: 'Classic trap: a fridge is both dark and cold. Seeds do not need light to germinate.' },
      { id: 'lc-050', type: 'oeq', level: 3, marks: 2,
        stem: 'Mei did the experiment in the table to find out if seeds need water to germinate. (a) What did she change? (b) What did she measure?',
        figure: meiExp,
        model: '(a) Whether the cotton wool was wet or dry (the presence of water). (b) The number of seeds that germinated.',
        keys: [['water', 'wet', 'dry'], ['number of seeds', 'germinated']],
        explain: 'Change one thing (water). Measure the result (number of seeds that germinated).' },
      { id: 'lc-051', type: 'oeq', level: 3, marks: 2,
        stem: 'Look at Mei\'s experiment again. Name two things she must keep the same in both dishes to make it a fair test.',
        figure: meiExp,
        model: 'Any two: the type of seed, the number of seeds, the amount of cotton wool, the size of the dish, the place / temperature.',
        keys: [['type of seed', 'kind of seed', 'number of seeds', 'size of seed'], ['cotton wool', 'dish', 'place', 'temperature', 'light']],
        explain: 'Everything except the water must be the same, so that only water can cause the difference.' },
      { id: 'lc-052', type: 'oeq', level: 3, marks: 1,
        stem: 'In Mei\'s experiment, only 9 of the 10 seeds in dish A germinated. Why was it better to use 10 seeds in each dish instead of 1?',
        figure: meiExp,
        model: 'Some seeds may not germinate even with water (they may be damaged or dead), so using more seeds makes the result more reliable.',
        keys: [['reliable', 'may not germinate', 'damaged', 'dead', 'accurate']],
        explain: 'If she had used just one seed and it happened to be dead, she would wrongly conclude water does not help.' },
      { id: 'lc-053', type: 'oeq', level: 2, marks: 1,
        stem: 'A mosquito larva keeps swimming up to the surface of the water. Why?',
        figure: null,
        model: 'To take in air (to breathe).',
        keys: [['air', 'breathe', 'oxygen']],
        explain: 'The larva and pupa live in water but take in air at the water surface.' },
      { id: 'lc-054', type: 'oeq', level: 3, marks: 2,
        stem: 'The table shows the life cycles of animals A, B and C. Which animal could be a grasshopper? Give a reason.',
        figure: threeAnimals,
        model: 'A. A grasshopper has a 3-stage life cycle (egg, nymph, adult) with no pupa stage.',
        keys: [['A'], ['nymph', 'no pupa', '3 stages', 'three stages']],
        explain: 'B is a 4-stage insect like a butterfly or beetle; C is a frog.' },
      { id: 'lc-055', type: 'oeq', level: 2, marks: 2,
        stem: 'Kumar said, "All young animals look like their parents." Using one example, explain why he is wrong.',
        figure: null,
        model: 'A caterpillar (larva) does not look like the adult butterfly. / A tadpole does not look like the adult frog.',
        keys: [['butterfly', 'caterpillar', 'larva', 'mosquito', 'beetle', 'frog', 'tadpole'], ['does not look like', 'different', 'not like']],
        explain: 'Name an animal whose young looks different, and say that it does not look like the adult.' },
      { id: 'lc-056', type: 'oeq', level: 2, marks: 2,
        stem: 'The diagram shows the life cycle of a frog. Stage B lives only in water, has a tail and no legs. Stage C has four legs and a short tail. Name stages B and C.',
        figure: cycle(['Egg', 'B', 'C', 'Adult frog']),
        model: 'B is the tadpole. C is the froglet (young frog).',
        keys: [['tadpole'], ['froglet', 'young frog']],
        explain: 'Tadpole (tail, no legs, water) → froglet (four legs, short tail) → adult (no tail).' },
      { id: 'lc-057', type: 'oeq', level: 3, marks: 2,
        stem: 'A butterfly lays its eggs on the underside of the leaves of one kind of plant. Give two reasons why.',
        figure: null,
        model: 'When the caterpillars hatch, the leaves are food they can eat straight away. Under the leaf, the eggs are hidden from predators (birds) and protected from rain and hot sun.',
        keys: [['food', 'eat', 'feed'], ['hidden', 'predators', 'birds', 'rain', 'sun', 'protect']],
        explain: 'Reason 1: food for the larva. Reason 2: protection for the eggs.' },
      { id: 'lc-058', type: 'oeq', level: 3, marks: 2,
        stem: 'Jane put green bean seeds on wet cotton wool inside a dark cupboard at room temperature. After 3 days, the seeds germinated. What does this tell you about germination?',
        figure: null,
        model: 'Seeds do not need light to germinate. They only need water, air and warmth.',
        keys: [['light'], ['not need', 'do not need', 'not needed', 'not necessary']],
        explain: 'The seeds had no light but still germinated, so light is not needed for germination.' },
      { id: 'lc-059', type: 'oeq', level: 2, marks: 1,
        stem: 'The pupa of a butterfly hardly moves and does not feed. Siti thinks it is dead. What is actually happening inside the pupa?',
        figure: null,
        model: 'It is alive; its body is changing into an adult butterfly.',
        keys: [['adult', 'butterfly', 'changing', 'developing']],
        explain: 'The pupa is a resting stage — the larva\'s body is changing into the adult.' }
    ]
  });
})();
