"use strict";
// P3 Science — Diversity of Materials (MOE Primary Science Syllabus 2023, Diversity theme).
// Syllabus properties: strength, flexibility, ability to float/sink in water, waterproof, transparency.
// Deliberately excluded: hardness (not in the 2023 property list) and heat conduction (P4 Heat).

// ---------- shared figures (data only) ----------
const MAT_FIG_STRENGTH_SETUP = `<svg viewBox="0 0 320 170" width="100%" style="max-width:340px" xmlns="http://www.w3.org/2000/svg" font-family="sans-serif" font-size="12" fill="none" stroke="currentColor">
  <rect x="10" y="50" width="70" height="14"/><line x1="18" y1="64" x2="18" y2="150"/><line x1="72" y1="64" x2="72" y2="150"/>
  <rect x="240" y="50" width="70" height="14"/><line x1="248" y1="64" x2="248" y2="150"/><line x1="302" y1="64" x2="302" y2="150"/>
  <rect x="60" y="44" width="200" height="6" stroke-width="2"/>
  <line x1="160" y1="50" x2="160" y2="80"/>
  <rect x="148" y="80" width="24" height="12"/><rect x="148" y="94" width="24" height="12"/><rect x="148" y="108" width="24" height="12"/>
  <text x="105" y="36" fill="currentColor" stroke="none">strip of material</text>
  <text x="180" y="104" fill="currentColor" stroke="none">weights</text>
  <text x="22" y="164" fill="currentColor" stroke="none">desk</text>
  <text x="256" y="164" fill="currentColor" stroke="none">desk</text>
</svg>`;

const MAT_FIG_FLEX_SETUP = `<svg viewBox="0 0 320 170" width="100%" style="max-width:340px" xmlns="http://www.w3.org/2000/svg" font-family="sans-serif" font-size="12" fill="none" stroke="currentColor">
  <rect x="10" y="44" width="110" height="18"/><line x1="20" y1="62" x2="20" y2="150"/><line x1="110" y1="62" x2="110" y2="150"/>
  <rect x="88" y="30" width="20" height="40"/>
  <line x1="108" y1="40" x2="250" y2="40" stroke-dasharray="4 3"/>
  <path d="M108 42 Q180 46 248 72" stroke-width="3"/>
  <line x1="248" y1="72" x2="248" y2="96"/><rect x="234" y="96" width="28" height="22"/>
  <rect x="280" y="26" width="14" height="110"/>
  <line x1="280" y1="40" x2="286" y2="40"/><line x1="280" y1="56" x2="286" y2="56"/><line x1="280" y1="72" x2="286" y2="72"/><line x1="280" y1="88" x2="286" y2="88"/>
  <line x1="266" y1="40" x2="266" y2="72" stroke-width="1.5"/><path d="M262 66 L266 72 L270 66"/>
  <text x="76" y="22" fill="currentColor" stroke="none">clamp</text>
  <text x="130" y="30" fill="currentColor" stroke="none">strip (before)</text>
  <text x="150" y="84" fill="currentColor" stroke="none">strip bends</text>
  <text x="226" y="134" fill="currentColor" stroke="none">mass</text>
  <text x="272" y="152" fill="currentColor" stroke="none">ruler</text>
  <text x="40" y="164" fill="currentColor" stroke="none">table</text>
</svg>`;

const MAT_FIG_LIGHT_SETUP = `<svg viewBox="0 0 320 120" width="100%" style="max-width:340px" xmlns="http://www.w3.org/2000/svg" font-family="sans-serif" font-size="12" fill="none" stroke="currentColor">
  <rect x="10" y="48" width="60" height="24" rx="4"/><path d="M70 48 L84 40 L84 80 L70 72"/>
  <line x1="90" y1="60" x2="140" y2="60" stroke-dasharray="4 3"/><path d="M134 56 L140 60 L134 64"/>
  <rect x="148" y="24" width="10" height="72"/>
  <line x1="164" y1="60" x2="220" y2="60" stroke-dasharray="4 3"/><path d="M214 56 L220 60 L214 64"/>
  <rect x="226" y="44" width="60" height="32" rx="4"/>
  <text x="22" y="98" fill="currentColor" stroke="none">torch</text>
  <text x="120" y="112" fill="currentColor" stroke="none">sheet of material</text>
  <text x="228" y="98" fill="currentColor" stroke="none">light sensor</text>
</svg>`;

const MAT_TBL_STRENGTH = `<table><tr><th>Material</th><th>Number of weights the strip held before it broke</th></tr>
<tr><td>A</td><td>5</td></tr><tr><td>B</td><td>12</td></tr><tr><td>C</td><td>2</td></tr><tr><td>D</td><td>8</td></tr></table>`;

const MAT_TBL_FLEX = `<table><tr><th>Material</th><th>How far the end of the strip moved down (cm)</th></tr>
<tr><td>P</td><td>2</td></tr><tr><td>Q</td><td>9</td></tr><tr><td>R</td><td>5</td></tr><tr><td>S</td><td>0</td></tr></table>`;

const MAT_TBL_WATER = `<table><tr><th>Material</th><th>Volume of water at the start (ml)</th><th>Volume of water left after 5 minutes (ml)</th></tr>
<tr><td>W</td><td>50</td><td>50</td></tr><tr><td>X</td><td>50</td><td>32</td></tr><tr><td>Y</td><td>50</td><td>45</td></tr><tr><td>Z</td><td>50</td><td>50</td></tr></table>`;

const MAT_TBL_KEN = `<table><tr><th>Material</th><th>Length of strip (cm)</th><th>Number of weights held before it broke</th></tr>
<tr><td>Wood</td><td>20</td><td>6</td></tr><tr><td>Plastic</td><td>30</td><td>3</td></tr><tr><td>Metal</td><td>20</td><td>10</td></tr></table>`;

SCI.registerTopic({
  id: "materials",
  title: "Materials", emoji: "🪵",
  theme: "Diversity",
  moeRef: "Relate the use of various types of materials (wood, metal, ceramic, rubber, glass, plastic, fabric) to their physical properties; compare the physical properties of materials based on strength, flexibility, ability to float/sink in water, waterproof and transparency (para)",
  notes: [
    { title: "Objects are made of materials",
      body: "Common materials: wood, metal, plastic, glass, rubber, fabric (cloth), ceramic and paper. One object can be made of more than one material. Example: a pair of scissors has metal blades and a plastic handle. We choose a material because of its properties." },
    { title: "Strength",
      body: "Strength is the ability of a material to hold heavy loads without breaking. Metal and wood are strong. Paper tears easily, so it is not strong. Glass and ceramic break easily when they are dropped or knocked. To compare strength, count how many weights a strip can hold before it breaks: more weights = stronger." },
    { title: "Flexibility",
      body: "Flexibility is the ability of a material to bend without breaking. Rubber, cloth, paper and many plastics are flexible. Glass and ceramic are not flexible: they break instead of bending. Thin metal (like aluminium foil) can be flexible too." },
    { title: "Waterproof",
      body: "A waterproof material does NOT absorb water. Plastic, rubber, glass, metal and ceramic are waterproof. Cotton cloth, paper and sponge absorb water, so they are not waterproof. Useful for raincoats, umbrellas, boots and cups." },
    { title: "Float or sink",
      body: "An object floats if it stays on or near the surface of the water. Wood, cork and polystyrene float. Glass marbles, steel nails, coins and ceramic sink. Plastics can float or sink depending on the plastic, so test it to find out!" },
    { title: "Transparent, translucent, opaque",
      body: "These three words tell us how much light a material allows to pass through. Learn each word AND what it means: markers often give the mark for the meaning. TRANSPARENT: allows most light to pass through, so we can see clearly through it (clear glass, clear plastic). TRANSLUCENT: allows some light to pass through, so things seen through it look blurry (frosted glass, tracing paper). OPAQUE: does not allow light to pass through, so we cannot see through it at all (wood, metal, ceramic, cardboard). In an answer, write both: 'Clear glass is transparent. It allows most light to pass through, so we can see outside clearly.'" },
    { title: "Answering 'why is it made of...?'",
      body: "Markers want TWO parts: the property + why it suits the use. Example: 'Plastic is waterproof (property), so the raincoat does not absorb rain and keeps the body dry (use).' Just writing 'plastic is good' gets no marks." },
    { title: "Fair test experiments",
      body: "Change only ONE thing: the type of material. Keep everything else the same: size, length and thickness of the strips, the mass of each weight, the amount of water. Measure the result (number of weights, how far it bends, volume of water left). Repeat the experiment to make the results more reliable." },
    { title: "Reading results tables",
      body: "Strength: held MORE weights before breaking = stronger. Flexibility: bent MORE (moved down further) = more flexible. Waterproof: LESS water left in the beaker = the material absorbed more water. If no water was absorbed, the material is waterproof." }
  ],
  items: [
    // ---------------- MCQ, level 1 ----------------
    { id: "mat-001", type: "mcq", level: 1,
      stem: "Which property tells us whether a material can bend without breaking?",
      figure: null,
      options: ["Strength", "Flexibility", "Waterproof", "Transparency"],
      answer: 1,
      explain: "Flexibility is the ability to bend without breaking. Strength is about holding heavy loads without breaking." },
    { id: "mat-002", type: "mcq", level: 1,
      stem: "A material that does not absorb water is ______.",
      figure: null,
      options: ["flexible", "strong", "waterproof", "transparent"],
      answer: 2,
      explain: "Waterproof means the material does not absorb water, like plastic or rubber." },
    { id: "mat-003", type: "mcq", level: 1,
      stem: "Which material allows most light to pass through it?",
      figure: null,
      options: ["Wood", "Ceramic", "Metal", "Clear glass"],
      answer: 3,
      explain: "Clear glass allows most light to pass through, so we can see clearly through it: it is transparent. Wood, ceramic and metal do not allow light to pass through: they are opaque." },
    { id: "mat-004", type: "mcq", level: 1,
      stem: "Which of these objects will float on water?",
      figure: null,
      options: ["A steel nail", "A glass marble", "A wooden ice-cream stick", "A metal coin"],
      answer: 2,
      explain: "Wood floats on water. Steel nails, glass marbles and metal coins sink." },
    { id: "mat-005", type: "mcq", level: 1,
      stem: "Which material absorbs water?",
      figure: null,
      options: ["Rubber", "Plastic", "Cotton cloth", "Glass"],
      answer: 2,
      explain: "Cotton cloth absorbs water, so it is not waterproof. Rubber, plastic and glass are waterproof." },
    { id: "mat-006", type: "mcq", level: 1,
      stem: "What does the 'strength' of a material mean?",
      figure: null,
      options: ["Its ability to bend without breaking", "Its ability to hold heavy loads without breaking", "Its ability to let light pass through", "Its ability to float on water"],
      answer: 1,
      explain: "Strength = holding heavy loads without breaking. Bending without breaking is flexibility." },
    { id: "mat-007", type: "mcq", level: 1,
      stem: "Which material is the most flexible?",
      figure: null,
      options: ["Glass", "Ceramic", "Rubber", "Wood"],
      answer: 2,
      explain: "Rubber can bend easily without breaking. Glass and ceramic break instead of bending, and a wooden block hardly bends." },
    { id: "mat-008", type: "mcq", level: 1,
      stem: "The blades of a pair of scissors are made of metal. Why?",
      figure: null,
      options: ["Metal is strong.", "Metal allows light to pass through.", "Metal floats on water.", "Metal absorbs water."],
      answer: 0,
      explain: "Metal is strong, so the blades do not break when cutting. Metal does not let light through, sinks, and does not absorb water." },
    { id: "mat-009", type: "mcq", level: 1,
      stem: "Which material breaks most easily when it is dropped on the floor?",
      figure: null,
      options: ["Rubber", "Cloth", "Plastic", "Glass"],
      answer: 3,
      explain: "Glass is not strong and breaks easily when dropped. Rubber, cloth and plastic usually do not break." },
    { id: "mat-010", type: "mcq", level: 1,
      stem: "Which material allows only SOME light to pass through, so things seen through it look blurry?",
      figure: null,
      options: ["Tracing paper", "Clear glass", "A wooden board", "A metal tray"],
      answer: 0,
      explain: "Tracing paper is translucent: it allows some light to pass through. Clear glass is transparent: it allows most light to pass through. Wood and metal are opaque: they do not allow light to pass through." },
    { id: "mat-051", type: "mcq", level: 1,
      stem: "A material that allows most light to pass through is ______.",
      figure: null,
      options: ["opaque", "translucent", "transparent", "waterproof"],
      answer: 2,
      explain: "Transparent means it allows most light to pass through, so we can see clearly through it, like clear glass. Translucent allows only some light through. Opaque does not allow light to pass through." },
    { id: "mat-052", type: "mcq", level: 1,
      stem: "A wooden door does not allow light to pass through. Wood is ______.",
      figure: null,
      options: ["opaque", "transparent", "translucent", "flexible"],
      answer: 0,
      explain: "Opaque means it does not allow light to pass through, so we cannot see through it. Transparent allows most light through; translucent allows some light through. A wooden door is not flexible: it does not bend." },

    // ---------------- MCQ, level 2 ----------------
    { id: "mat-011", type: "mcq", level: 2,
      stem: "Mrs Tan wants a tablecloth that can be folded easily. Which property of the material is the most important?",
      figure: null,
      options: ["Strength", "Flexibility", "Ability to float", "Transparency"],
      answer: 1,
      explain: "To fold the tablecloth, the material must bend without breaking, so it must be flexible." },
    { id: "mat-012", type: "mcq", level: 2,
      stem: "Balloons are made of rubber. Which property of rubber makes it suitable?",
      figure: null,
      options: ["Rubber is flexible and can stretch without breaking.", "Rubber allows most light to pass through.", "Rubber absorbs water.", "Rubber sinks in water."],
      answer: 0,
      explain: "A balloon must stretch as air is blown in. Rubber is flexible, so it bends and stretches without breaking." },
    { id: "mat-013", type: "mcq", level: 2,
      stem: "A fish tank must hold water and let us see the fish clearly. Which material is the most suitable?",
      figure: null,
      options: ["Wood", "Cloth", "Ceramic", "Glass"],
      answer: 3,
      explain: "Glass is waterproof AND transparent: it allows most light to pass through, so we can see the fish. Wood and ceramic are opaque: they do not allow light to pass through. Cloth absorbs water." },
    { id: "mat-014", type: "mcq", level: 2,
      stem: "A shower curtain must be waterproof and flexible. Which material is the most suitable?",
      figure: null,
      options: ["Paper", "Plastic", "Glass", "Wood"],
      answer: 1,
      explain: "Plastic is waterproof and flexible. Paper absorbs water; glass and wood are not flexible." },
    { id: "mat-015", type: "mcq", level: 2,
      stem: "Bathroom floor tiles are often made of ceramic. Which property of ceramic makes it suitable?",
      figure: null,
      options: ["It is waterproof.", "It is flexible.", "It allows most light to pass through.", "It floats on water."],
      answer: 0,
      explain: "The bathroom floor gets wet. Ceramic is waterproof, so the tiles do not absorb the water." },
    { id: "mat-016", type: "mcq", level: 2,
      stem: "Which object is correctly matched to a property of its material?",
      figure: null,
      options: ["Window glass: does not allow light to pass through", "Paper bag: waterproof", "Ceramic bowl: flexible", "Rubber gloves: waterproof"],
      answer: 3,
      explain: "Rubber is waterproof. Window glass allows most light through, paper absorbs water, and ceramic is not flexible." },
    { id: "mat-017", type: "mcq", level: 2,
      stem: "Mei wants her bathroom window to let light in, but she does not want people outside to see in clearly. Which material should she use?",
      figure: null,
      options: ["Clear glass", "Frosted glass", "Wood", "Metal"],
      answer: 1,
      explain: "Frosted glass is translucent: it allows some light to pass through, so the room is bright but people cannot see in clearly. Clear glass is transparent, so people could see in. Wood and metal are opaque: they do not allow light to pass through, so the room would be dark." },
    { id: "mat-018", type: "mcq", level: 2,
      stem: "Raju wants to build a small raft that floats and can carry a heavy load without breaking. Which material is the most suitable?",
      figure: null,
      options: ["Glass", "Ceramic", "Paper", "Wood"],
      answer: 3,
      explain: "Wood floats and is strong. Glass and ceramic sink and break easily. Paper absorbs water and is not strong." },
    { id: "mat-053", type: "mcq", level: 2,
      stem: "Which material is correctly matched to how much light passes through it?",
      figure: null,
      options: ["Clear plastic: opaque", "Cardboard: transparent", "Tracing paper: opaque", "Frosted glass: translucent"],
      answer: 3,
      explain: "Frosted glass is translucent: it allows some light to pass through, so things look blurry. Clear plastic is transparent (allows most light through). Cardboard is opaque (does not allow light to pass through). Tracing paper is translucent, not opaque." },
    { id: "mat-019", type: "mcq", level: 2,
      stem: "Plates for young children are often made of plastic instead of ceramic. Why?",
      figure: null,
      options: ["Plastic allows most light to pass through.", "Plastic absorbs water.", "Plastic does not break easily when dropped.", "Plastic sinks in water."],
      answer: 2,
      explain: "Young children may drop their plates. Ceramic breaks easily, but plastic usually does not, so the child will not get hurt by sharp pieces." },
    { id: "mat-020", type: "mcq", level: 2,
      stem: "Siti hung weights one at a time on strips of different materials until each strip broke. The results are shown. Which material is the strongest?",
      figure: MAT_TBL_STRENGTH,
      options: ["A", "B", "C", "D"],
      answer: 1,
      explain: "B held the most weights (12) before it broke, so B is the strongest. C is the weakest." },
    { id: "mat-021", type: "mcq", level: 2,
      stem: "Jane set up the experiment shown. She added weights one at a time until the strip broke. Which property of the material was she testing?",
      figure: MAT_FIG_STRENGTH_SETUP,
      options: ["Flexibility", "Strength", "Waterproof", "Transparency"],
      answer: 1,
      explain: "Adding weights until the strip breaks tests how heavy a load it can hold: its strength." },
    { id: "mat-022", type: "mcq", level: 2,
      stem: "Ahmad clamped strips of four materials to a table and hung the same mass at the end of each. He measured how far the end of each strip moved down. Which material is the most flexible?",
      figure: MAT_TBL_FLEX,
      options: ["P", "Q", "R", "S"],
      answer: 1,
      explain: "The strip that bends the most (moves down the furthest) is the most flexible. Q moved down 9 cm. S did not bend at all." },

    // ---------------- MCQ, level 3 ----------------
    { id: "mat-023", type: "mcq", level: 3,
      stem: "Ahmad used this set-up to find out which material is the most flexible. Which of these must he keep the same to make it a fair test?",
      figure: MAT_FIG_FLEX_SETUP,
      options: ["The type of material", "The length and thickness of each strip", "How far each strip bends", "The number of strips that break"],
      answer: 1,
      explain: "Only the type of material is changed. The length and thickness (and the mass hung) are kept the same. How far each strip bends is what he measures." },
    { id: "mat-024", type: "mcq", level: 3,
      stem: "Kim put 50 ml of water into each of four beakers. She put a same-sized piece of a different material into each beaker for 5 minutes, took it out and measured the water left. Which materials are waterproof?",
      figure: MAT_TBL_WATER,
      options: ["X only", "X and Y", "Y and Z", "W and Z"],
      answer: 3,
      explain: "W and Z still had 50 ml left, so they absorbed no water: they are waterproof. X and Y absorbed some water." },
    { id: "mat-025", type: "mcq", level: 3,
      stem: "Leon needs a material to make a float for his fishing line. It must float on water and must not absorb water. Which material should he choose?",
      figure: `<table><tr><th>Material</th><th>Floats on water?</th><th>Absorbs water?</th></tr>
<tr><td>A</td><td>Yes</td><td>Yes</td></tr><tr><td>B</td><td>Yes</td><td>No</td></tr><tr><td>C</td><td>No</td><td>No</td></tr><tr><td>D</td><td>No</td><td>Yes</td></tr></table>`,
      options: ["A", "B", "C", "D"],
      answer: 1,
      explain: "Only B floats AND does not absorb water (it is waterproof). A floats but absorbs water; C and D sink." },
    { id: "mat-026", type: "mcq", level: 3,
      stem: "A window on a boat must be waterproof, allow us to see clearly outside, and not break easily. Which material is the most suitable?",
      figure: `<table><tr><th>Material</th><th>Waterproof?</th><th>How much light passes through</th><th>Breaks easily?</th></tr>
<tr><td>P</td><td>Yes</td><td>Most</td><td>Yes</td></tr><tr><td>Q</td><td>Yes</td><td>Most</td><td>No</td></tr><tr><td>R</td><td>No</td><td>Some</td><td>No</td></tr><tr><td>S</td><td>Yes</td><td>None</td><td>No</td></tr></table>`,
      options: ["P", "Q", "R", "S"],
      answer: 1,
      explain: "Q has all three: waterproof, transparent (allows most light to pass through, so we see clearly), and does not break easily. P breaks easily. R absorbs water and is only translucent. S is opaque: it does not allow light to pass through." },
    { id: "mat-027", type: "mcq", level: 3,
      stem: "Nurul shone a torch through sheets of materials A, B and C, one at a time. A light sensor measured the amount of light that passed through: A = 90 units, B = 40 units, C = 0 units. Which material is most likely tracing paper?",
      figure: MAT_FIG_LIGHT_SETUP,
      options: ["A, because it allowed the most light to pass through", "B, because it allowed some light to pass through", "C, because it allowed no light to pass through", "A, because it allowed no light to pass through"],
      answer: 1,
      explain: "Tracing paper is translucent: it allows SOME light to pass through, like B. A allowed the most light through, so it is transparent, like clear glass or clear plastic. C allowed no light through, so it is opaque, like wood or cardboard." },
    { id: "mat-054", type: "mcq", level: 3,
      stem: "Nurul shone a torch through sheets of materials A, B and C, one at a time. A light sensor measured the amount of light that passed through: A = 90 units, B = 40 units, C = 0 units. Which sentence describes the materials correctly?",
      figure: MAT_FIG_LIGHT_SETUP,
      options: ["A is opaque, B is translucent, C is transparent.", "A is translucent, B is transparent, C is opaque.", "A is transparent, B is translucent, C is opaque.", "A is transparent, B is opaque, C is translucent."],
      answer: 2,
      explain: "A let the most light through (90 units), so it is transparent: it allows most light to pass through. B let some light through (40 units), so it is translucent. C let no light through (0 units), so it is opaque: it does not allow light to pass through." },
    { id: "mat-028", type: "mcq", level: 3,
      stem: "Ken wanted to find out which material is the strongest. His results are shown. Why is his experiment NOT a fair test?",
      figure: MAT_TBL_KEN,
      options: ["He used strips of different lengths.", "He used three different materials.", "He counted the number of weights.", "The metal strip held the most weights."],
      answer: 0,
      explain: "Ken changed the type of material (correct) but ALSO the length: the plastic strip was 30 cm. Only one thing should change in a fair test." },
    { id: "mat-029", type: "mcq", level: 3,
      stem: "Meiling says, 'All objects made of metal are not flexible.' Which object shows that she is wrong?",
      figure: null,
      options: ["An iron nail", "A steel spoon", "Aluminium foil", "A metal pot"],
      answer: 2,
      explain: "Aluminium foil is a thin metal sheet that bends easily without breaking, so some metal objects are flexible." },
    { id: "mat-030", type: "mcq", level: 3,
      stem: "Which statement about materials is correct?",
      figure: null,
      options: ["All plastics float on water.", "All waterproof materials allow light to pass through.", "A strong material is always flexible.", "One material can have more than one property."],
      answer: 3,
      explain: "Glass, for example, is waterproof AND allows most light through. Some plastics sink; metal is waterproof but lets no light through; a thick wooden block is strong but not flexible." },

    // ---------------- OEQ, level 1 ----------------
    { id: "mat-031", type: "oeq", level: 1, marks: 1,
      stem: "Name one material that is waterproof.",
      figure: null,
      model: "Plastic (or rubber, glass, metal, ceramic).",
      keys: [ ["plastic", "rubber", "glass", "metal", "ceramic"] ],
      explain: "Any waterproof material earns the mark. Cloth and paper are wrong: they absorb water." },
    { id: "mat-032", type: "oeq", level: 1, marks: 2,
      stem: "What does it mean when we say a material is flexible?",
      figure: null,
      model: "The material can bend without breaking.",
      keys: [ ["bend"], ["without breaking", "not break", "does not break"] ],
      explain: "Both parts are needed: it bends AND it does not break." },
    { id: "mat-055", type: "oeq", level: 1, marks: 2,
      stem: "Tracing paper is translucent. (a) What does 'translucent' mean? (b) What do things look like when we see them through tracing paper?",
      figure: null,
      model: "(a) Translucent means it allows some light to pass through. (b) Things seen through it look blurry; we cannot see them clearly.",
      keys: [ ["allows some light", "some light"], ["blurry", "cannot see them clearly", "not clear"] ],
      explain: "Know the word AND its meaning. Translucent = allows some light to pass through. Transparent = allows most light to pass through. Opaque = does not allow light to pass through." },
    { id: "mat-033", type: "oeq", level: 1, marks: 2,
      stem: "Raincoats are made of plastic. State the property of plastic that makes it suitable, and explain why.",
      figure: null,
      model: "Plastic is waterproof, so it does not absorb the rain and keeps the person's body dry.",
      keys: [ ["waterproof", "does not absorb water"], ["dry", "not get wet", "keeps the rain out"] ],
      explain: "Markers look for: the property (waterproof) + why it suits the use (keeps the body dry)." },
    { id: "mat-034", type: "oeq", level: 1, marks: 2,
      stem: "Windows are usually made of clear glass. Explain why.",
      figure: null,
      model: "Clear glass is transparent. It allows most light to pass through, so the room is bright and we can see outside clearly.",
      keys: [ ["transparent", "allows most light", "lets most light pass through"], ["see outside", "see through", "room is bright", "bright"] ],
      explain: "Property (transparent: allows most light to pass through) + use (we can see out / the room is bright). Either the word 'transparent' or its meaning earns the first mark; writing both is safest." },

    // ---------------- OEQ, level 2 ----------------
    { id: "mat-035", type: "oeq", level: 2, marks: 2,
      stem: "Bath towels are made of cotton cloth. Explain why.",
      figure: null,
      model: "Cotton cloth absorbs water, so it can dry our body after a bath.",
      keys: [ ["absorbs water", "absorb water", "absorbs"], ["dry our body", "dry", "wipe"] ],
      explain: "Here NOT being waterproof is useful: the towel absorbs water to dry us." },
    { id: "mat-036", type: "oeq", level: 2, marks: 2,
      stem: "Rubber bands are made of rubber. Explain why rubber is suitable.",
      figure: null,
      model: "Rubber is flexible, so the rubber band can bend and stretch without breaking to hold things together.",
      keys: [ ["flexible", "bend", "stretch"], ["without breaking", "not break", "hold things", "tie"] ],
      explain: "Property (flexible) + use (stretches around things without breaking)." },
    { id: "mat-037", type: "oeq", level: 2, marks: 2,
      stem: "Why is glass NOT a suitable material for a young child's drinking cup?",
      figure: null,
      model: "Glass is not strong and breaks easily. If the child drops the cup, it may break and the sharp pieces can hurt the child.",
      keys: [ ["breaks easily", "break easily", "not strong"], ["hurt", "cut", "injure", "sharp", "dropped"] ],
      explain: "Property (breaks easily / not strong) + why that matters (the child may get hurt)." },
    { id: "mat-038", type: "oeq", level: 2, marks: 2,
      stem: "Give two reasons why wood is a suitable material for making a raft.",
      figure: null,
      model: "Wood can float on water. Wood is strong, so it can hold the weight of people without breaking.",
      keys: [ ["float"], ["strong", "hold heavy", "carry", "not break"] ],
      explain: "One mark for 'floats', one mark for 'strong / holds a heavy load without breaking'." },
    { id: "mat-039", type: "oeq", level: 2, marks: 2,
      stem: "A shower curtain is made of plastic, not cotton cloth. Explain why plastic is more suitable.",
      figure: null,
      model: "Plastic is waterproof and does not absorb water. Cotton cloth absorbs water, so the curtain would become wet and heavy.",
      keys: [ ["plastic is waterproof", "plastic does not absorb", "waterproof"], ["cloth absorbs", "cloth will absorb", "cloth is not waterproof", "cloth would get wet"] ],
      explain: "Compare both materials: plastic does not absorb water, cloth does." },
    { id: "mat-040", type: "oeq", level: 2, marks: 2,
      stem: "A fish tank is made of glass. State two properties of glass that make it suitable for a fish tank.",
      figure: null,
      model: "Glass is waterproof, so it can hold water without absorbing it. Glass is transparent. It allows most light to pass through, so we can see the fish clearly.",
      keys: [ ["waterproof", "does not absorb water"], ["transparent", "allows most light", "see the fish"] ],
      explain: "One mark for each property linked to its use. For the second mark, 'transparent' or 'allows most light to pass through' both name the property." },
    { id: "mat-041", type: "oeq", level: 2, marks: 2,
      stem: "Some bathroom windows are made of frosted glass instead of clear glass. Explain why.",
      figure: null,
      model: "Frosted glass is translucent. It allows only some light to pass through. The bathroom is still bright, but people outside cannot see in clearly.",
      keys: [ ["translucent", "some light"], ["cannot see in clearly", "cannot see clearly", "privacy", "blurry"] ],
      explain: "Property (translucent: allows some light to pass through) + use (light gets in, but no one can see in clearly). Either the word or its meaning earns the first mark." },
    { id: "mat-042", type: "oeq", level: 2, marks: 2,
      stem: "Cups are often made of ceramic. State one property of ceramic that makes it suitable for a cup, and explain why.",
      figure: null,
      model: "Ceramic is waterproof, so it does not absorb the drink and the cup can hold the drink without leaking.",
      keys: [ ["waterproof", "does not absorb"], ["hold the drink", "hold water", "not leak", "drink"] ],
      explain: "Property (waterproof) + use (holds the drink). Waterproof is the safest property to give: ceramic still breaks easily if the cup is dropped." },

    // ---------------- OEQ, level 3 (experiments) ----------------
    { id: "mat-043", type: "oeq", level: 3, marks: 2,
      stem: "Look at Siti's results. Which material, A or D, is more suitable for making a shelf to hold heavy books? Explain your answer using the results.",
      figure: MAT_TBL_STRENGTH,
      model: "Material D. It held more weights (8) than A (5) before it broke, so it is stronger and can hold heavy books without breaking.",
      keys: [ ["D"], ["more weights", "8", "stronger"] ],
      explain: "Name the material AND use the evidence from the table: more weights held = stronger." },
    { id: "mat-044", type: "oeq", level: 3, marks: 2,
      stem: "Jane used this set-up to test the strength of four materials. (a) What did she change in her experiment? (b) State one thing she must keep the same.",
      figure: MAT_FIG_STRENGTH_SETUP,
      model: "(a) The type of material. (b) The size (length, width, thickness) of the strips / the mass of each weight / the distance between the desks.",
      keys: [ ["type of material"], ["length", "width", "thickness", "size", "mass of each weight", "distance between the desks"] ],
      explain: "Changed variable = type of material. Many answers are accepted for 'kept the same'." },
    { id: "mat-045", type: "oeq", level: 3, marks: 1,
      stem: "Jane repeated her experiment two more times. Why did she do this?",
      figure: MAT_FIG_STRENGTH_SETUP,
      model: "To make her results more reliable.",
      keys: [ ["reliable"] ],
      explain: "SG markers want the word 'reliable'. Repeating does NOT make the test fair; it checks the results are consistent." },
    { id: "mat-046", type: "oeq", level: 3, marks: 2,
      stem: "Ahmad used this set-up to find out which material is the most flexible. (a) What did he measure? (b) How can he tell which material is the most flexible?",
      figure: MAT_FIG_FLEX_SETUP,
      model: "(a) How far the end of each strip moved down (bent), using the ruler. (b) The strip that bent the most / moved down the furthest is the most flexible.",
      keys: [ ["how far", "distance", "how much"], ["bent the most", "bends the most", "moved down the most", "furthest"] ],
      explain: "Flexibility is measured by how much the strip bends with the same mass." },
    { id: "mat-047", type: "oeq", level: 3, marks: 2,
      stem: "Look at Kim's results. Which material, X or Y, absorbed more water? Explain using the results.",
      figure: MAT_TBL_WATER,
      model: "X. Only 32 ml of water was left in its beaker, which is less than for Y (45 ml), so X absorbed more water (18 ml).",
      keys: [ ["X"], ["less water left", "32", "18"] ],
      explain: "Less water left in the beaker means the material absorbed more water." },
    { id: "mat-048", type: "oeq", level: 3, marks: 2,
      stem: "In Kim's experiment, why did she put the same amount of water (50 ml) into every beaker?",
      figure: MAT_TBL_WATER,
      model: "To make it a fair test, so that only the type of material was changed.",
      keys: [ ["fair test", "fair"], ["only the type of material", "only one", "type of material"] ],
      explain: "Keeping the amount of water the same means any difference is caused only by the material." },
    { id: "mat-049", type: "oeq", level: 3, marks: 2,
      stem: "Ken's experiment was not a fair test. Suggest how he should change it, and explain why.",
      figure: MAT_TBL_KEN,
      model: "He should use strips of the same length (and size) for all three materials, so that only the type of material is changed.",
      keys: [ ["same length", "same size"], ["only the type of material", "only one", "fair"] ],
      explain: "Fix: same length. Reason: only one variable (the material) should change." },
    { id: "mat-050", type: "oeq", level: 3, marks: 3,
      stem: "Mei thinks a plastic ruler is more flexible than a wooden ruler. Describe how she can carry out a fair test to check this.",
      figure: null,
      model: "Use a plastic ruler and a wooden ruler of the same length and thickness. Clamp each one to the edge of a table in the same way and hang the same mass at the end. Measure how far each ruler bends. The ruler that bends more is more flexible.",
      keys: [ ["same length", "same size", "same thickness"], ["same mass", "same weight", "same load"], ["measure how far", "how much it bends", "bends more", "distance"] ],
      explain: "Three marks: keep the rulers the same size; hang the same mass; measure how much each bends." }
  ]
});
