// swift-tools-version: 6.0
//
// Math Quest Island - native iOS packages.
//
// ONE manifest, one target per module, each module living in its own directory under
// ios/Packages/. That keeps the module = package = lane boundary of the iOS brief while
// leaving a single test command at ios/ that runs every module's suite - which is the
// gate Kai can actually hold (Command Line Tools, no Xcode, macOS target only).
//
// Kai-testable today:
//   MQContent   pure Swift, the seam. Foundation only, no Apple UI frameworks.
//   MQEngineJS  the JavaScriptCore implementation of MQContent.QuestionSource.
//               JavaScriptCore is a macOS framework, so this builds and tests here.
//
// RUNNING THE TESTS ON KAI
//   ./test.command                (from ios/)   <- THE GATE. Use this.
//   swift test --toolset kai-toolset.json       <- runs the suites; is NOT the gate
// Command Line Tools ships Testing.framework outside every default search path and no
// XCTest at all, so a bare `swift test` on Kai FAILS TO BUILD: the suites
// `import Testing` unconditionally, giving `error: no such module 'Testing'` and exit 1.
// (An earlier version of this comment said it compiled the suites and silently ran ZERO
// of them. Measured at d060bb3, that is not what happens - it is loud.) kai-toolset.json
// supplies the search path and rpaths; test.command applies it when the ACTIVE TOOLCHAIN
// has no XCTest, not when /Applications/Xcode.app happens to be missing.
//
// `swift test` alone is not the gate even where it runs: the gate is test.command, which
// also verifies the committed engine bundle's own bytes against js/ and FAILS when zero
// tests execute - a --filter matching nothing used to exit 0. See ios/gate-floor.txt.
// Deliberately no `unsafeFlags` in this manifest: they would follow the package into
// every consumer, and this manifest is meant to be added to an Xcode project as-is.
//
// FOR SUPREME (the Xcode box): add the app target on top WITHOUT touching these
// modules. File > Add Package Dependencies > Add Local... and pick the `ios` directory;
// the app target then depends on the `MQContent` product AND ONLY THAT - the contract
// rule is that UI never imports MQEngineJS. The composition root wires one
// `JSQuestionEngine` at launch and hands it up as a `QuestionSource`.
// New modules (MQDesign, MQProgress, MQQuest, MQPatchwerk, MQFigures, MQServices) are
// added here as further targets + products in the same shape.
import PackageDescription

let package = Package(
    name: "MathQuestIsland",
    platforms: [
        .iOS(.v17),
        .macOS(.v14)   // macOS is the Kai gate: the suites run on this platform
    ],
    products: [
        .library(name: "MQContent", targets: ["MQContent"]),
        .library(name: "MQEngineJS", targets: ["MQEngineJS"])
    ],
    targets: [
        .target(
            name: "MQContent",
            path: "Packages/MQContent/Sources/MQContent"
        ),
        .testTarget(
            name: "MQContentTests",
            dependencies: ["MQContent"],
            path: "Packages/MQContent/Tests/MQContentTests"
        ),
        .target(
            name: "MQEngineJS",
            dependencies: ["MQContent"],
            path: "Packages/MQEngineJS/Sources/MQEngineJS",
            resources: [
                // Generated by `npm run build:engine` at the repo root and COMMITTED, so
                // a fresh clone - and Xcode on Supreme - builds with no Node step.
                .copy("Resources")
            ]
        ),
        .testTarget(
            name: "MQEngineJSTests",
            dependencies: ["MQEngineJS", "MQContent"],
            path: "Packages/MQEngineJS/Tests/MQEngineJSTests"
        )
    ]
)
